export { HeroSection } from './hero'
export { Display } from './display'
export { StyliaAbout } from './about-me'
export { LuxuryGallery } from './gallery'
export { ExpertiseSection } from './expertise'
export { StyleCTASection } from './style-cta'
export { ClienteleSection } from './clientele'
export { TestimonialsSection } from './testimonials'
